version: "3"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      JWT_SECRET: "your_jwt_secret_key"
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "assignment-test"
      POSTGRES_PASSWORD: "annielmiftasya5"
